version: '3.6'

services:
  amule:
    container_name: amule
    build:
      context: builders/amule
    image: user/amule
    ports:
      - "4662:4662/tcp"
      - "4665:4665/udp"
      - "4672:4672/udp"
      - "4711:4711/tcp"
    volumes:
      - /mnt/hitachi1T/amuledock/Incoming:/var/lib/amule/.aMule/Incoming
      - /mnt/hitachi1T/amuledock/Temp:/var/lib/amule/.aMule/Temp
    environment:
      - ECPASSWORD=admin.1234
      - WEBPASSWORD=admin.1234


